### ISSUE TITLE
Display velocity on existing PCA

### ISSUE THREAD

**Issue by yanwengong** [velocyto-team/velocyto.R#47]
I wonder whether there is way to display velocity on existing PCA (rows are cells; columns are PCs). It seems show.velocity.on.embedding.cor needs the embedding matrix (after tsne or largeVis); pca.velocity.plot cannot take pca as input and it will generate its own PCA.

**Comment by Puriney** [comment]
See official [tutorial](http://pklab.med.harvard.edu/velocyto/notebooks/R/SCG71.nb.html). Either `show.velocity.on.embedding.cor` or `show.velocity.on.embedding.eu`  is the function you need. It has two required inputs. 1) `emb`, user's existing 2D space, e.g., PCA or tSNE. It is a matrix with cell names as row names and two columns for the 2D space. 2) `vel`, the R object saving the velocyto.R's result.

Because you are using a dimension reduction space generated separately, be careful that the cell names should be consistent to the ones present in the velocyto's analytical result, otherwise error probably comes up.

One more seemingly optional parameter is the `cell.colors`. You should explictly specify the color for each cell. Otherwise, the default are black points.

**Comment by yanwengong** [comment]
Thanks a lot! Got it to work.
